### ISSUE TITLE
Request: Demo without depending on Rust

### ISSUE THREAD

**Issue by guest271314** [WebAssembly/wasi-messaging#11]
Installing Rust toolchain on a system requires over 1GB - before downloading any crates. That is prohibitive for a temporary file system running on RAM, where only 3GB is available. Downloading crates, i.e., tokio, can easily result in no space left on device error.

**Comment by danbugs** [comment]
Is this an issue w/ regards to: https://github.com/danbugs/wasi-messaging-demo? If so, I think that might be a better place for it – I'll try and keep issues here mostly related to the interface itself.
