### ISSUE TITLE
Aligning messaging interfaces 

### ISSUE THREAD

**Issue by salaboy** [WebAssembly/wasi-messaging#6]
Hi team, 

My name is [Mauricio Salatino](https://twitter.com/salaboy) and I am working on a project called Dapr (https://dapr.io/), we have a component called pubs which basically defines a common API for publishing messages [https://docs.dapr.io/reference/api/pubsub_api/](https://docs.dapr.io/reference/api/pubsub_api/).

With the same intention that I've created this issue in the keyvalue initiative (https://github.com/WebAssembly/wasi-keyvalue/issues/7) I am writing here to see if there is some way we can align interfaces.

**Comment by Mossaka** [comment]
Happy to, and I have replied to the wasi-keyvalue side. I'd like to keep our conversation on that side and closing this one.
